#change parameter managementGroupIds from line 9 accordingly / single or multiple managementGroupIds
#check line 35 branch match master/main
#if you want to leverage parameters, add them in line 58

trigger: none

pr: none

parameters:
- name: managementGroupIds
  type: object
  default:
    - '4bb13780-3466-49d9-b930-cc38f34ba8be' #e.g. 55ca6640-f705-4a6d-8574-549c57acf4ed (can be Tenant Root Group Management Group Id or child Management Group Id)
    #- '<yourManagementGroupId_1>' #use this (and you may create more lines) if you want to run against multiple Management Groups
- name: subscriptionQuotaIdWhitelistParameters
  type: object
  default:
    - undefined

variables:
  ServiceConnection: AzAdServicePrincipalInsights
  ManagementGroupId: ${{ join(',',parameters.managementGroupIds) }}
  SubscriptionQuotaIdWhitelist: ${{ join(',',parameters.subscriptionQuotaIdWhitelistParameters) }}
  WikiDir: wiki
  CsvDelimiter: ;
  ScriptDir: pwsh #e.g. myFolder/pwsh
  Script: AzADServicePrincipalInsights.ps1

schedules:
- cron: "0 6,16 * * *"
  displayName: at 6am, 4pm
  always: true
  branches:
    include:
    - main #CHECK branch 'main' is applicable? - delete me :)

jobs:
- job: AzADServicePrincipalInsights
  timeoutInMinutes: 0

  pool:
    vmImage: 'ubuntu-20.04'

  steps:
  - task: PowerShell@2
    inputs:
      targetType: 'filePath'
      filePath: $(System.DefaultWorkingDirectory)/$(ScriptDir)/prerequisites.ps1
    displayName: 'Prerequisites check'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  - task: AzurePowerShell@4
    inputs:
      azureSubscription: '$(ServiceConnection)'
      scriptType: filePath
      pwsh: true
      scriptPath: '$(System.DefaultWorkingDirectory)/$(ScriptDir)/$(Script)'
      scriptArguments: '-OutputPath $(WikiDir) -ScriptPath $(ScriptDir) -ManagementGroupId $(ManagementGroupId)'
      azurePowerShellVersion: latestVersion
    displayName: 'Run AzADServicePrincipalInsights v1'
  - powershell: |
      write-host "#################################"
      write-host "Push AzADServicePrincipalInsights output to repository"
      write-host "#################################"
      $executionDateTimeInternationalReadable = get-date -format "dd-MMM-yyyy HH:mm:ss"
      $currentTimeZone = (Get-TimeZone).Id
      git config --global user.email "AzADServicePrincipalInsightsPipeline@azdo.com"
      $PipelineInfo = "Pipeline: '$(Build.DefinitionName)' 'rev $(Build.BuildNumber)' (Project: $([uri]::EscapeDataString("$(System.TeamProject)")); Repository: $(Build.Repository.Name); Branch: $(Build.SourceBranchName) Commit: $(Build.SourceVersion))"
      git config --global user.name "$PipelineInfo"
      git config pull.rebase false
      git add --all
      git commit -m "wiki $executionDateTimeInternationalReadable ($currentTimeZone)"
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin HEAD:$(Build.SourceBranchName)
    displayName: 'Push AzADServicePrincipalInsights v1 output to repository'
